# Generated by Django 5.2.8 on 2025-11-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicenow_sys_id', models.CharField(help_text='ServiceNow system ID', max_length=32, unique=True)),
                ('number', models.CharField(help_text='Change request number (e.g., CHG0030001)', max_length=40)),
                ('short_description', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('state', models.CharField(max_length=20)),
                ('priority', models.CharField(max_length=10)),
                ('jira_issue_key', models.CharField(blank=True, help_text='Linked Jira issue key', max_length=50, null=True)),
                ('github_repo', models.CharField(blank=True, help_text='GitHub repository name', max_length=100, null=True)),
                ('github_pr_number', models.IntegerField(blank=True, help_text='GitHub pull request number', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Change Request',
                'verbose_name_plural': 'Change Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['servicenow_sys_id'], name='integration_service_234ce9_idx'), models.Index(fields=['number'], name='integration_number_93e312_idx'), models.Index(fields=['jira_issue_key'], name='integration_jira_is_4f93c0_idx')],
            },
        ),
    ]
